sudo: true
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
env:
  - DJANGO=django18
  - DJANGO=django19
  - DJANGO=django110
  - DJANGO=django111
before_install:
  - sudo apt-get update && sudo apt-get build-dep python-imaging
  - sudo apt-get install -y postgresql-9.5-postgis-2.3
  - sudo service postgresql restart
install:
 - pip install tox
addons:
  postgresql: "9.4"
services:
  - postgresql
before_script:
  - psql -U postgres -c "create extension postgis"
  - psql -U postgres -c "create extension hstore"
  - psql -c 'create database model_mommy;' -U postgres
  - psql -c 'create database model_mommy_test;' -U postgres
script:
  - TOX_TEST_PASSENV="TRAVIS TRAVIS_JOB_ID TRAVIS_BRANCH" tox -e py${TRAVIS_PYTHON_VERSION//[.]/}-$DJANGO-{postgresql}
  - TOX_TEST_PASSENV="TRAVIS TRAVIS_JOB_ID TRAVIS_BRANCH" tox -e py${TRAVIS_PYTHON_VERSION//[.]/}-$DJANGO-{sqlite}
